services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: verbamind_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me-for-local-only}
      POSTGRES_DB: verbamind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # ---> ADD THIS LINE BELOW <---
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
